from utils.summarizer import generate_summary, extract_key_concepts
from utils.quiz import generate_quiz
from utils.qa import answer_question


# Whisper handles speech recognition.
# Hugging Face handles lecture summary and concept extraction.
# The quiz and lecture Q&A are generated by Hugging Face models as part of the local NLP pipeline.


def generate_study_material(transcript: str) -> dict:
    """Generate study material in the exact structure expected by the Streamlit app."""
    summary = generate_summary(transcript)
    key_concepts = extract_key_concepts(transcript, summary)
    quiz = generate_quiz(summary, transcript, key_concepts)

    return {
        "summary": summary,
        "key_concepts": key_concepts,
        "quiz": quiz,
    }


def ask_lecture(transcript: str, question: str) -> str:
    """Answer a lecture question using a pretrained Hugging Face QA model."""
    return answer_question(transcript, question)

